name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Получает полную историю коммитов
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Set up Git user
      run: |
        git config --global user.name "LUSTX0"
        git config --global user.email "bazarim111@yandex.by"

    - name: Increment version
      run: dotnet tool install -g nbgv || true

    - name: Prepare release
      run: nbgv prepare-release

    
    # - name: Update Swagger version
    #   run: |
    #     new_version=$(nbgv get-version)
    # - name: Get version
    #   id: get-version
    #   run: echo "::set-output name=new_version::$(nbgv get-version -p)"
    - name: Install NerdBank.GitVersioning
      run: dotnet tool install -g NerdBank.GitVersioning --version "3.*"  # Установка NerdBank.GitVersioning

    - name: Determine version
      id: gitversion
      run: |
        dotnet-gitversion /updateprojectfiles
        echo "::set-output name=version::$(dotnet-gitversion /showvariable SemVer)"

    - name: Print version
      run: echo "The new version is ${{ steps.gitversion.outputs.version }}"    
        

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./out

    

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/library-p:${{ github.run_number }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/library-p:${{ github.run_number }}

    